### Get all persons
GET http://localhost:3004/api/persons

### Get info page
GET http://localhost:3004/info

### Get number by id
GET http://localhost:3004/api/persons/3

### Remove number by id
DELETE http://localhost:3004/api/persons/3

### Add new number
POST http://localhost:3004/api/persons
Content-Type: application/json

{
	"name": "Daniel Albul",
	"number": "+38442234545"
}
